name: raspberrypi

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: look around
        run: ls

#      - name: Update Container
#        run: git pull

      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Cleanup Unused Images
        run: docker image prune -f
