name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

#      - name: set cd
#        run: cd && cd DiscordChickenMessageBot

#      - name: Update Container
#        run: git pull

      - name: Run Container
        run: sudo docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Cleanup Unused Images
        run: sudo docker image prune -f
